stages:
- test
- build

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

lint:
  stage: test
  image: node:20.10.0
  script:
    - cd swcotd
    - npm ci
    - npm run lint

test:
  stage: test
  image: node:20.10.0
  script:
    - cd swcotd
    - npm ci
    - npm run test -- --run

build:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - echo "${CI_JOB_TOKEN}" | docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} --password-stdin
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA} .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
