stages:
- test
- build

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

lint:
  stage: test
  image: node:20.10.0
  script:
    - cd swcotd
    - npm ci
    - npm run lint

test:
  stage: test
  image: node:20.10.0
  script:
    - cd swcotd
    - npm ci
    - npm run test -- --run

build:
  stage: build
  image: node:20.10.0
  script:
    - cd swcotd
    - npm ci
    - npm run build
  artifacts:
    when: always
    paths:
      - swcotd/.next
    expire_in: 1 days 6 hrs
  cache:
    key:
      files:
        - swcotd/.nvmrc
        - swcotd/package-lock.json
    paths:
      - swcotd/node_modules
